Buddies/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Buddies.Data_Access;

namespace Buddies.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {
        // Default administrationpage.
        // GET: Administration
        public ActionResult Index()
        {
            var dao = new ProfileDAO();
            return View(dao.GetAllProfiles());
        }

        /// <summary>
        /// Toggle the active status
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ToggleActivation(FormCollection collection)
        {
            var dao = new ProfileDAO();

            // update
            var result = dao.ToggleProfileActivation(collection["userID"]);

            // create the view and display the proper message
            ViewData.Add("Message", string.Empty);
            ViewBag.Message = result == 1 ? "De status is succesvol bijgewerkt" : "Er is iets misgegaan, probeer opnieuw";

            return View();
        }
    }
}

Buddies/Controllers/ProfileController.cs
using Buddies.Data_Access;
using Buddies.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Buddies.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }

        // GET: Profile/Details/5
        public ActionResult Details(String id)
        {
            ProfileDAO _dao = new ProfileDAO();
            ProfileViewModel mijnProfiel = new ProfileViewModel();
            mijnProfiel = _dao.getProfileById(id);
            
            return View(mijnProfiel);
        }

        // GET: Profile/Create
        public ActionResult Create(RegisterViewModel model)
        { 
            CreateViewModel myCreateViewModel = new CreateViewModel(model);

            return View(myCreateViewModel);
        }

        // POST: Profile/Create
        [HttpPost]
        public ActionResult Create(FormCollection form)
        {
            ProfileDAO _dao = new ProfileDAO();

            _dao.createProfile(form);

            return RedirectToAction("Details", new { id = form["UserID"] });
        }

        // GET: Profile/Edit/5
        public ActionResult Edit(String id)
        {
            ProfileDAO _profileDao = new ProfileDAO();
            UpdateProfileViewModel mijnNieuwModel = new UpdateProfileViewModel();                        
            ProfileViewModel mijnProfiel = new ProfileViewModel();

            mijnProfiel = _profileDao.getProfileById(id);

            mijnNieuwModel = _profileDao.createUpdateProfile(mijnProfiel);
            
            
            return View(mijnNieuwModel);
        }

        // POST: Profile/Edit/5
        [HttpPost]
        public ActionResult Edit(FormCollection collection)
        {
            try
            {
                ProfileDAO _dao = new ProfileDAO();

                _dao.updateProfile(collection);

                return RedirectToAction("Details", new { id = collection["UserID"] });
            }
            catch
            {
                return View();
            }
        }

        // GET: Profile/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Profile/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Buddies/Views/Administration/Index.cshtml
@using Buddies.Models
@using GridMvc.Html
@model Buddies.Models.SearchViewModel

@{
    ViewBag.Title = "Beheersconsole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>Onderstaande lijst geeft een overzicht van alle profielen die zich bevinden in Buddies.<br/>
    Na iedere naam staat een link waarmee u het gewenste profiel kan bekijken. Via de profieldetails kan het gewenste profiel gedeactiveerd worden.
</p>
@Html.Grid(Model.Profiles).Columns(cols =>
    {
        cols.Add(c => c.UserName).Titled("Gebruikersnaam");
        cols.Add(c => c.Land).Titled("Land van herkomst");
        cols.Add()
            .Sanitized(false)
            .Encoded(false)
            .RenderValueAs(c => @Html.ActionLink("bekijk profiel", "Details", "Profile", new { id = c.UserID }, null));
    }).WithPaging(10)

Buddies/Views/Administration/ToggleActivation.cshtml
@{
    ViewBag.Title = "Berichtgeving";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>@ViewBag.Message</p>
<p>
    <a id="backLink" href="#">Terug naar het overzicht</a>
</p>